apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    - image: docker.io/vibolrim290/skaffold-jib-demo
      jib: {}
  tagPolicy:
    sha256: {}
  local:
    push: true
deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml
    flags:
      global:
        - --kubeconfig=dev.kubeconfig
        - --context=dev-context