apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-jib-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skaffold-jib-demo
  template:
    metadata:
      labels:
        app: skaffold-jib-demo
    spec:
      containers:
      - name: skaffold-jib-demo
        image: docker.io/vibolrim290/skaffold-jib-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: skaffold-jib-demo
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30081
  selector:
    app: skaffold-jib-demo 